// import { Images } from '../data/images';

const InitialState = {
  selectedDog: '',
  dogData: {
    1: {
      name: 'Tala',
      breed: 'German Shepard',
      age: '3 years',
      gender: 'female',
      size: 'Large',
      description: 'Tala is a puppy at heart, and love sto roll around in the dirt. She is still figuring out how big her body is.',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/tala4.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/tala1.jpg',
        2: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/tala2.jpg',
        3: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/tala3.jpg',
        4: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/tala4.jpg',
      },
      key: 1,
    },
    2: {
      name: 'Mobley',
      age: '4 years',
      gender: 'male',
      size: 'Small',
      breed: 'Chihuahua / Corgi Mix',
      description: 'Tala is a puppy at heart, and love sto roll around in the dirt. She is still figuring out how big her body is.',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley4.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley1.jpg',
        2: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley2.jpg',
        3: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley3.jpg',
        4: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley4.jpg',
        5: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley5.jpg',
        6: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley6.jpg',
        7: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley7.jpg',
        8: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley8.jpg',
        9: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley9.jpg',
        10: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/Mobley10.jpg',
      },
      key: 2,
    },
    3: {
      name: 'Sadie',
      age: '10 years',
      gender: 'female',
      size: 'Large',
      breed: 'Golden Retreiver',
      description: 'Tala is a puppy at heart, and love sto roll around in the dirt. She is still figuring out how big her body is.',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/sadie1.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/sadie1.jpg',
        2: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/sadie2.jpg',
      },
      key: 3,
    },
    4: {
      name: 'Doug',
      age: '2 years',
      gender: 'male',
      breed: 'Chihuahua',
      size: 'Small',
      description: 'Doug is a cute little dog who loves to play with other dogs and hang out in the sun.',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/doug3.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/doug1.jpg',
        2: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/doug2.jpg',
        3: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/doug3.jpg',
        4: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/doug4.jpg',
        5: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/doug5.jpg',
        6: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/doug6.jpg',
        7: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/doug7.jpg',
      },
      key: 4,
    },
    5: {
      name: 'Susan',
      age: '2 years',
      gender: 'female',
      breed: 'Cocker Spaniel',
      size: 'Medium',
      description: 'Tala is a puppy at heart, and love sto roll around in the dirt. She is still figuring out how big her body is.',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/susan.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/susan.jpg',
        2: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/susan2.jpg',
      },
      key: 5,
    },
    6: {
      name: 'Buko',
      age: '3 years',
      gender: 'male',
      breed: 'Chuihuahua / Corgi Mix',
      size: 'Medium',
      description: 'Tala is a puppy at heart, and love sto roll around in the dirt. She is still figuring out how big her body is.',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/buko1.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/buko1.jpg',
        2: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/buko2.jpg',
        3: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/buko3.jpg',
        4: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/buko4.jpg',
        5: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/buko5.jpg',
      },
      key: 6,
    },
    7: {
      name: 'Aoife',
      age: '12 years',
      gender: 'female',
      breed: 'Labrador Retreiver',
      size: 'Large',
      description: 'Her name is Gaelic for "warrior princess". She’s always looking for spoils (of food).',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/aoife1.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/aoife1.jpg',
        2: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/aoife2.jpg',
        3: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/aoife3.jpg',
      },
      key: 7,
    },
    8: {
      name: 'Rusty',
      age: '6 years',
      gender: 'male',
      breed: 'Golden Retreiver',
      size: 'Large',
      description: 'Only the most famous Instagram dog from portland. Hotties only ',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/rusty1.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/rusty1.jpg',
        2: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/rusty2.jpg',
        3: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/rusty3.jpg',
        4: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/rusty4.jpg',
        5: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/rusty5.jpg',
      },
      key: 8,
    },
    9: {
      name: 'Alana',
      age: '1 years',
      gender: 'female',
      breed: 'Austrailian Shepard',
      description: 'Only the most famous Instagram dog from portland. Hotties only ',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/alana1.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/alana1.jpg',
      },
      key: 9,
    },
    10: {
      name: 'Lola',
      age: '4 years',
      gender: 'female',
      breed: 'Shiba Inu',
      size: 'Medium',
      description: 'Only the most famous Instagram dog from portland. Hotties only ',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/lola.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/lola.jpg',
      },
      key: 10,
    },
    11: {
      name: 'Marko',
      age: '4 years',
      gender: 'male',
      breed: 'Siberian Husky',
      size: 'Large',
      description: 'Only the most famous Instagram dog from portland. Hotties only ',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/marko1.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/marko1.jpg',
        2: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/marko2.jpg',
        3: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/marko3.jpg',
        4: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/marko4.jpg',
      },
      key: 11,
    },
    12: {
      name: 'Roman',
      age: '1 years',
      gender: 'male',
      breed: 'Austrailian Shepard',
      size: 'Large',
      description: 'Only the most famous Instagram dog from portland. Hotties only ',
      profilePhoto: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/roman1.jpg',
      photos: {
        1: 'https://storage.googleapis.com/for-dogs-only.appspot.com/photos/roman1.jpg',
      },
      key: 12,
    },
  },
};

export default InitialState;
