# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ForDogsOnly' do
  pod 'UrbanAirship-iOS-SDK', '~>9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ForDogsOnly

  target 'ForDogsOnly-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ForDogsOnlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'ForDogsOnly-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for ForDogsOnly-tvOS

#   target 'ForDogsOnly-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
